name: omniware_payment_gateway_totalxsoftware
description: "Omniware Payment Gateway Plugin for Flutter under TotalxSoftware"
version: 1.0.3
homepage: "https://github.com/totalxsoftwaredevelopers/omniware_payment_gateway_totalxsoftware"

environment:
  sdk: ^3.5.3
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  payment_gateway_plugin: ^3.0.6
  cloud_firestore: ^5.5.0
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true

screenshots:
  - description: "https://www.totalx.in"
    path: assets/images/totalx.png
  - description: "https://omniware.in/"
    path: assets/images/omniware.png
